### ISSUE TITLE
Unleveled: Several UI styles missing (no Leveled)

### ISSUE THREAD

**Issue by Mernom** [Arrenton/Leveled#14]
List of UI styles as they worked (or not) on my system
- health bar 1 working
- health bar 2 working
- health bar 3 working
- health bar 4 working
- elsword not working
- health bar 6 only mana working
- galaxy not working
- metroid prime working
- KH2 not working
- KH style small leveled not working
- medium not
- large not
- same for non leveled
- zelda ALTTP working
- Zelda HP working
- Zelda OOT working
- zenda MM working
- Life gems working
- FRAXY setting working (same for all)

Also, after reinstalling the mod the game seems to crash the first time I use the /uneveled command on a given character. (crash log added)
![terraria_ error 2019-01-29 10_50_15 am](https://user-images.githubusercontent.com/47146928/51911958-c7e51580-23db-11e9-9aab-9ebf1e838401.png)

All issues presist when Unleveled is the only active mod.

- Consistent
- Not using Leveled

Unleveled 1.6

**Comment by webmilio** [comment]
Closed as not an actual issue, as discussion in bug-discussion. There are some weird things happening with Unleveled's configuration.
