### ISSUE TITLE
(Thorium Mod Compatibility) Radiant Damage and other healing effects not scaled

### ISSUE THREAD

**Issue by BladeofRagnarok** [Arrenton/Leveled#25]
Made sure to check every weapon and item I could find. Radiant damage and the healing effects appear to be unaffected with the mod and do vanilla damage. Well, vanilla for Thorium anyways.

**Comment by webmilio** [comment]
I assume you haven't read the changelog
`*!!Native support for other mods has been removed and left to be done through the API.!!`

or the forum post:
`We're no longer responsible for mod support, although we have plans of making addons that will kickstart support.`
