### ISSUE TITLE
Banner Abnormal Damage

### ISSUE THREAD

**Issue by help4cura** [Arrenton/Leveled#28]
Abnormal damage occurs when there is a banner effect (very high damage 2x~3x)

Version Leveled 1.0.1 / tmodloader 0.10.1.5

**Comment by webmilio** [comment]
https://terraria.gamepedia.com/Banners_(enemy)

Would you say you do more damage than that ?

**Comment by Kaylenx** [comment]
Absolutely, banners are increasing damage more than +100%.
My testing was done on Critical Mode, not sure if this is helpful.

**Comment by Arrenton** [comment]
This issue affected projectiles causing nearly a 500% damage boost. Fixed in 1.0.4.
