### ISSUE TITLE
Multiplayer modded mobs issue

### ISSUE THREAD

**Issue by Haiysei** [Arrenton/Leveled#31]
When playing on a multiplayer server, any modded mobs don't spawn at the level of the current biome they spawned in. Instead they spawn at lvl 19. This issue only occurs on servers.

**Comment by webmilio** [comment]
Pretty sure we confirmed that was from Overhaul.

**Comment by Haiysei** [comment]
No, overhaul doesn't affect leveled in that way, I did some more testing and it was Multiplayer servers that caused it

**Comment by webmilio** [comment]
I've personally never encountered that bug, let me try to repro it.

**Comment by Arrenton** [comment]
I have not been able to replicate this issue. I'm running only Leveled in multiplayer and everything is scaling just fine.

**Comment by Arrenton** [comment]
Fixed in 1.0.4.
