### ISSUE TITLE
Power Flower changed stat numbers stay blue.

### ISSUE THREAD

**Issue by webmilio** [Arrenton/Leveled#4]
The blue numbers in the PowerFlower stay blue even after applying.

- Consistent
- Beta

Leveled 1.0.0.12

![image](https://user-images.githubusercontent.com/836345/50570394-3d1ae780-0d57-11e9-86fa-fa9385e46bc3.png)

**Comment by WhatABeautifulDuwang** [comment]
Changing armors or any accessory that affects Attack or defence affect the blue numbers alongside the base stats
![image](https://user-images.githubusercontent.com/20447627/50570453-8d4f7500-0d6a-11e9-9df2-95d26aa213db.png)
![image](https://user-images.githubusercontent.com/20447627/50570456-d273a700-0d6a-11e9-8ab9-ad05aa8e23a6.png)

**Comment by webmilio** [comment]
Resolved.
