### ISSUE TITLE
Tooltip of healing items don't show

### ISSUE THREAD

**Issue by WhatABeautifulDuwang** [Arrenton/Leveled#7]
Whenever a healing item enters your inventory, the tooltip that shows the % and amount of healing dealt by that item dissapears.

- Consistent
- Beta

![image](https://user-images.githubusercontent.com/20447627/50614210-cf89cb00-0ebe-11e9-8d39-e6dec686a7c5.png)
Though the tooltip does show on any NPC's that sell healing items
![image](https://user-images.githubusercontent.com/20447627/50614286-0fe94900-0ebf-11e9-9398-1dd6dac79556.png)

Leveled 1.0.0.15

**Comment by webmilio** [comment]
Might be the reason why QuickHeal doesn't work.

**Comment by SansDerp** [comment]
![image](https://user-images.githubusercontent.com/46334849/50621581-598c6080-0ecc-11e9-9ae5-86a6407ce2af.png)
Seems GUD to me!

Leveled 1.0.0.16

**Comment by Arrenton** [comment]
Unreproducable.
1.0.0.16
